### ISSUE TITLE
目前框架能支持训练停止之后继续训练么？

### ISSUE THREAD

**Issue by l22576283** [PatrickLib/captcha_recognition#2]
框架能否可以在暂停后再次按原有的进度继续训练，甚者能否支持模型保存后的后续优化训练？

**Comment by PatrickLib** [comment]
如果需要能够继续训练已经保存的模型，可以将train中sess.run(init_op)/sees.run(init)替换为saver.restore，代码可以参考captcha_recognize.py中使用saver加载模型参数。

**Comment by l22576283** [comment]
好的，但是我还有一个疑问？
我在看到别文章里面做训练的时候，每次训练的数据都是重新生成的。
而我们这里按描述里说的训练集只有50000，如果默认的批次大小每次128张图，那最多到390轮的时候数据应该已经用完了，那剩下的1W9千轮训练是在用重复的数据在训练？
这样不会有问题么？

**Comment by l22576283** [comment]
还有个问题就是继续训练的时候，训练集是从头开始的还是能从当时记录点开始？

**Comment by PatrickLib** [comment]
1.有学习率，所以不可能所有图片训练一次就直接找到局部最优；2.每一轮训练图片是随机组合的，建议看下https://hit-scir.gitbooks.io/neural-networks-and-deep-learning-zh_cn/content/chap3/c3s4.html 关于随机梯度下降的章节；3.因为训练集每轮的数据都是随机组合的，继续训练依然是随机没有记录，没有从头开始一说。
